import { useEffect, useState } from 'react';
import { ArrowRight, CalendarDays, CheckCircle2, Download, FileText, Mail, MapPin, Play, Send, Users } from 'lucide-react';
import { PageShell, SiteLayout } from '@/components/SiteLayout';
import { fetchEvents, fetchNews, formatEventDate, formatNewsDate } from '@/lib/data';
import type { EventItem, NewsItem } from '@/lib/supabase';

const heroImage = 'https://images.pexels.com/photos/20027734/pexels-photo-20027734.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const communityImage = 'https://images.pexels.com/photos/7712023/pexels-photo-7712023.jpeg?auto=compress&cs=tinysrgb&h=650&w=940';
const galleryImages = [
  'https://images.pexels.com/photos/7712023/pexels-photo-7712023.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'https://images.pexels.com/photos/8416867/pexels-photo-8416867.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'https://images.pexels.com/photos/17872545/pexels-photo-17872545.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
  'https://images.pexels.com/photos/8518777/pexels-photo-8518777.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
];

function SectionHeading({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) {
  return <div className="content-heading"><div className="eyebrow"><span /> {eyebrow}</div><h2>{title}</h2>{text && <p>{text}</p>}</div>;
}

function LinkCard({ title, text, href }: { title: string; text: string; href: string }) {
  return <a className="link-card" href={href}><div><h3>{title}</h3><p>{text}</p></div><ArrowRight size={18} /></a>;
}

function StatBand() {
  return <section className="stat-band"><div className="container stat-grid"><div><strong>4</strong><span>Aktif meclis</span></div><div><strong>8</strong><span>Çalışma komisyonu</span></div><div><strong>2009</strong><span>Kuruluş yılı</span></div><div><strong>∞</strong><span>Birlikte üretme fikri</span></div></div></section>;
}

export function HomePage() {
  const [news, setNews] = useState<NewsItem[]>([]);
  const [events, setEvents] = useState<EventItem[]>([]);
  useEffect(() => { Promise.all([fetchNews(), fetchEvents()]).then(([n, e]) => { setNews(n); setEvents(e); }); }, []);
  return <SiteLayout><main>
    <section className="hero" id="anasayfa"><div className="hero-image" style={{ backgroundImage: `url(${heroImage})` }} /><div className="hero-overlay" /><div className="container hero-content"><div className="hero-copy"><div className="eyebrow light"><span /> Ortak aklın, ortak geleceğin adresi</div><h1>Birlikte daha<br /><em>güçlü</em> bir kent.</h1><p>Küçükçekmece için fikri, emeği ve umudu olan herkesin buluşma noktasıyız.</p><div className="hero-actions"><a className="button button-light" href="/iletisim">Kent için sözüm var <ArrowRight size={17} /></a><a className="text-link light-link" href="/kurumsal/hakkimizda">Kent Konseyi nedir? <ArrowRight size={16} /></a></div></div><div className="hero-note"><span>01</span><div><strong>Yaşayan bir kent</strong><small>Hep birlikte üretiyoruz.</small></div></div></div></section>
    <section className="welcome-strip"><div className="container welcome-grid"><div className="eyebrow"><span /> Küçükçekmece Kent Konseyi</div><p>Yaşadığımız kenti birlikte düşünüyor, birlikte tasarlıyor ve birlikte güzelleştiriyoruz.</p><a className="text-link" href="/kurumsal/hakkimizda">Bizi tanıyın <ArrowRight size={16} /></a></div></section>
    <section className="section home-intro"><div className="container home-intro-grid"><div><SectionHeading eyebrow="Başkan Mesajı" title="Kentin geleceğinde sözümüz var." text="Küçükçekmece’yi ortak akılla, katılımcı demokrasiyle ve birlikte üretme kültürüyle geleceğe taşıyoruz." /><a className="text-link" href="/kurumsal/baskan-mesaji">Başkanın mesajını oku <ArrowRight size={16} /></a></div><div className="message-card"><span className="quote-mark">“</span><p>Bu kentte yaşayan herkesin fikri, emeği ve hayali bizim için değerli.</p><strong>Kent Konseyi Başkanı</strong></div></div></section>
    <section className="section quick-section"><div className="container"><SectionHeading eyebrow="Hızlı Erişim" title="Aradığınız bilgiye kolayca ulaşın." /><div className="quick-grid"><LinkCard title="Meclisler" text="Kentin farklı sesleriyle tanışın." href="/meclisler" /><LinkCard title="Komisyonlar" text="Çalışma alanlarımızı keşfedin." href="/komisyonlar" /><LinkCard title="Belgeler" text="Tüzük, rapor ve karar arşivi." href="/belgeler" /><LinkCard title="Etkinlik Takvimi" text="Yaklaşan buluşmaları görün." href="/takvim" /></div></div></section>
    <StatBand />
    <section className="section home-news"><div className="container"><div className="section-topline"><SectionHeading eyebrow="Gündemden" title="Son haberler" /><a className="text-link" href="/haberler">Tüm haberler <ArrowRight size={16} /></a></div><div className="news-grid">{news.slice(0, 3).map((item) => <article className="news-card red" key={item.id}><div className="news-meta"><span>{item.category}</span><time>{formatNewsDate(item.published_at)}</time></div><h3>{item.title}</h3><p className="news-excerpt">{item.excerpt}</p><a href={`/haberler/${item.id}`} aria-label={item.title}><ArrowRight size={18} /></a></article>)}</div></div></section>
    <section className="section home-events"><div className="container"><div className="section-topline"><SectionHeading eyebrow="Takvim" title="Yaklaşan etkinlikler" /><a className="text-link" href="/takvim">Takvimi gör <ArrowRight size={16} /></a></div><div className="events-list">{events.slice(0, 3).map((item) => <EventRow item={item} key={item.id} />)}</div></div></section>
    <section className="section gallery-preview"><div className="container"><div className="section-topline"><SectionHeading eyebrow="Galeri" title="Birlikte üretiyoruz." /><a className="text-link" href="/galeri">Galeriyi gör <ArrowRight size={16} /></a></div><div className="gallery-grid">{galleryImages.map((image, index) => <a href="/galeri" key={image}><img src={image} alt={`Kent Konseyi etkinlik görüntüsü ${index + 1}`} /></a>)}</div></div></section>
  </main></SiteLayout>;
}

function EventRow({ item }: { item: EventItem }) {
  const date = new Date(item.event_date);
  const months = ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara'];
  return <article className="event-row"><div className="event-date"><span className="event-day">{date.getDate()}</span><span className="event-month">{months[date.getMonth()]}</span></div><div className="event-body"><h3>{item.title}</h3><p>{item.description}</p><div className="event-meta">{item.event_time && <span><CalendarDays size={14} /> {item.event_time}</span>}{item.location && <span><MapPin size={14} /> {item.location}</span>}</div></div></article>;
}

export function InstitutionalPage({ slug = 'hakkimizda' }: { slug?: string }) {
  const content: Record<string, { title: string; eyebrow: string; description: string; heading: string; text: string[] }> = {
    hakkimizda: { title: 'Hakkımızda', eyebrow: 'Kurumsal', description: 'Küçükçekmece Kent Konseyi’nin kuruluşunu, değerlerini ve çalışma anlayışını keşfedin.', heading: 'Ortak aklın buluşma noktası.', text: ['Kent Konseyi; kent yaşamında yurttaşların, kurumların ve sivil toplumun ortak akıl etrafında buluştuğu demokratik bir platformdur.', 'Küçükçekmece’nin ihtiyaçlarını birlikte tespit ediyor, çözüm önerilerini katılımcı yöntemlerle geliştiriyor ve kentimizin geleceğine birlikte yön veriyoruz.'] },
    'kent-konseyi-hakkinda': { title: 'Küçükçekmece Kent Konseyi Hakkında', eyebrow: 'Kurumsal', description: 'Kent Konseyi’nin amacı, görevleri ve çalışma ilkeleri.', heading: 'Kentin her sesine açık bir yapı.', text: ['Kent Konseyleri, hemşehrilik bilincinin geliştirilmesi, kentin hak ve hukukunun korunması, sürdürülebilir kalkınma ve katılımcı yönetim anlayışının güçlendirilmesi için çalışır.', 'Bütün çalışmalarımızda kapsayıcılık, şeffaflık, gönüllülük ve ortak üretim ilkelerini esas alıyoruz.'] },
    'baskan-mesaji': { title: 'Başkan Mesajı', eyebrow: 'Kurumsal', description: 'Kent Konseyi Başkanımızın Küçükçekmece’ye mesajı.', heading: 'Birlikte daha güçlü bir Küçükçekmece.', text: ['Küçükçekmece’nin geleceğini, bu kente gönül veren herkesin katkısıyla birlikte kuracağımıza inanıyorum.', 'Kent Konseyi olarak gençlerden kadınlara, çocuklardan engelli yurttaşlarımıza kadar her sesin duyulduğu, her fikrin değer bulduğu bir katılım alanı oluşturmayı sürdüreceğiz.'] },
    'genel-kurul': { title: 'Genel Kurul', eyebrow: 'Kurumsal', description: 'Genel Kurul yapısı, toplantıları ve kararları.', heading: 'Kararların ortak zemini.', text: ['Genel Kurul, Kent Konseyi’nin en geniş katılımlı karar alma organıdır. Meclislerden, komisyonlardan ve kent paydaşlarından gelen öneriler burada değerlendirilir.', 'Toplantı gündemlerini, kararları ve çalışma raporlarını şeffaf biçimde paylaşırız.'] },
    'yurutme-kurulu': { title: 'Yürütme Kurulu', eyebrow: 'Kurumsal', description: 'Yürütme Kurulu üyeleri ve görevleri.', heading: 'Çalışmaları hayata geçiren ekip.', text: ['Yürütme Kurulu, Genel Kurul kararlarının uygulanmasını takip eder ve Kent Konseyi’nin çalışma programını koordine eder.', 'Kurul üyeleri, farklı meclis ve komisyonların ortak çalışmalarını bir araya getirir.'] },
    kurullar: { title: 'Kurullar', eyebrow: 'Kurumsal', description: 'Kent Konseyi bünyesinde görev yapan kurullar.', heading: 'Şeffaf ve düzenli çalışma.', text: ['Kent Konseyi çalışmalarının düzenli yürütülmesi için farklı görev alanlarına sahip kurullar birlikte çalışır.', 'Kurullarımızın görev, yetki ve sorumluluklarını ilgili yönetmeliklere uygun şekilde sürdürüyoruz.'] },
    tuzuk: { title: 'Tüzük', eyebrow: 'Kurumsal', description: 'Küçükçekmece Kent Konseyi tüzüğü.', heading: 'Çalışma ilkelerimizin çerçevesi.', text: ['Kent Konseyi’nin kuruluşunu, organlarını, görevlerini ve işleyişini belirleyen tüzük metnine buradan ulaşabilirsiniz.'] },
    yonetmelikler: { title: 'Yönetmelikler', eyebrow: 'Kurumsal', description: 'Kent Konseyi yönetmelikleri ve uygulama metinleri.', heading: 'Ortak çalışmanın kuralları.', text: ['Meclislerimizin ve komisyonlarımızın çalışma esaslarını açıklayan yönetmelikler, katılımcı sürecin düzenli işlemesini sağlar.'] },
    kvkk: { title: 'KVKK ve Gizlilik', eyebrow: 'Kurumsal', description: 'Kişisel verilerin korunması ve gizlilik politikamız.', heading: 'Verileriniz bizim için emanet.', text: ['Kişisel verilerinizi yalnızca iletişim ve başvuru süreçlerini yürütebilmek için, yürürlükteki mevzuata uygun olarak işleriz.', 'Aydınlatma metni, başvuru formu ve veri güvenliği politikamıza bu sayfadan ulaşabilirsiniz.'] },
  };
  const item = content[slug] ?? content.hakkimizda;
  return <PageShell title={item.title} eyebrow={item.eyebrow} description={item.description}><section className="section detail-section"><div className="container detail-grid"><div><SectionHeading eyebrow={item.eyebrow} title={item.heading} />{item.text.map((text) => <p className="body-copy" key={text}>{text}</p>)}<div className="detail-actions"><a className="button button-dark" href="/iletisim">Bize ulaşın <ArrowRight size={16} /></a><a className="text-link" href="/belgeler">Belgeler <ArrowRight size={16} /></a></div></div><div className="detail-aside"><img src={communityImage} alt="Kent Konseyi çalışmaları" /><div className="aside-note"><CheckCircle2 size={18} /><span>Şeffaflık, katılım ve ortak akıl</span></div></div></div></section></PageShell>;
}

export function CouncilsPage({ slug }: { slug?: string }) {
  const councils: Record<string, { title: string; description: string }> = { genclik: { title: 'Gençlik Meclisi', description: 'Gençlerin kent yaşamına, karar süreçlerine ve sosyal hayata katılımını güçlendiriyoruz.' }, kadin: { title: 'Kadın Meclisi', description: 'Kadınların kent yönetiminde ve toplumsal yaşamda eşit söz sahibi olması için çalışıyoruz.' }, ogrenci: { title: 'Öğrenci Meclisi', description: 'Çocukların ve öğrencilerin kent hakkını görünür kılıyor, fikirlerini dinliyoruz.' }, engelli: { title: 'Engelli Meclisi', description: 'Erişilebilir, kapsayıcı ve herkes için eşit bir kent hedefiyle çalışıyoruz.' }, hakkinda: { title: 'Meclisler Hakkında', description: 'Kent Konseyi meclisleri, farklı toplumsal grupların kendi ihtiyaçlarını ifade ettiği katılım kanallarıdır.' } };
  const item = slug ? councils[slug] ?? councils.hakkinda : { title: 'Meclislerimiz', description: 'Küçükçekmece’nin farklı seslerinin bir araya geldiği katılım kanalları.' };
  return <PageShell title={item.title} eyebrow="Meclisler" description={item.description}><section className="section"><div className="container"><div className="detail-grid"><div><SectionHeading eyebrow="Katılım" title={item.title === 'Meclislerimiz' ? 'Kentin farklı sesleri bir arada.' : 'Sözünüzü birlikte büyütelim.'} text={item.description} /><p className="body-copy">Meclisimiz, ilgili alanda çalışan yurttaşların, sivil toplum kuruluşlarının ve uzmanların gönüllü katılımıyla faaliyet gösterir. Toplantılarımız, çalışma gruplarımız ve kararlarımızı düzenli olarak paylaşırız.</p><a className="button button-dark" href="/iletisim">Meclise katıl <ArrowRight size={16} /></a></div><div className="feature-panel"><Users size={34} /><h3>Birlikte karar, birlikte gelecek</h3><p>Toplantı takvimi, haberler ve meclis belgeleri için bizi takip edin.</p><a className="text-link" href="/takvim">Takvime git <ArrowRight size={16} /></a></div></div><div className="subpage-grid">{['Çalışma alanları', 'Faaliyet ve haberler', 'Toplantı takvimi', 'Belgeler'].map((title) => <LinkCard title={title} text="Bu meclisin güncel içeriklerini inceleyin." href={title === 'Toplantı takvimi' ? '/takvim' : '/haberler'} key={title} />)}</div></div></section></PageShell>;
}

export function CommissionsPage({ slug }: { slug?: string }) {
  const names: Record<string, string> = { 'genclik-spor': 'Gençlik ve Spor Komisyonu', 'halkla-iliskiler': 'Halkla İlişkiler, Tanıtım ve İletişim Komisyonu', 'afet-kentsel-donusum': 'Afet ve Farkındalık / Kentsel Dönüşüm Komisyonu', ekonomi: 'Ekonomi Komisyonu', egitim: 'Eğitim Komisyonu', 'cevre-saglik': 'Çevre ve Sağlık Komisyonu', 'sanat-kultur': 'Sanat ve Kültür Komisyonu', muhtarlar: 'Muhtarlar Komisyonu' };
  const title = slug ? names[slug] ?? 'Komisyonlar' : 'Komisyonlar';
  return <PageShell title={title} eyebrow="Komisyonlar" description="Kent Konseyi’nin çalışma alanlarına göre oluşturduğu uzmanlık ve üretim grupları."><section className="section"><div className="container"><SectionHeading eyebrow="Birlikte üretiyoruz" title={slug ? 'Çalışma alanımız.' : 'Kent için çalışan ekipler.'} text="Komisyonlarımız, kent gündemindeki konulara odaklanır; araştırır, öneri geliştirir ve uygulanabilir çözümler üretir." /><div className="commission-directory">{Object.entries(names).map(([key, name], index) => <LinkCard title={`0${index + 1}  ${name}`} text="Komisyonun amacı, çalışma alanları ve güncel faaliyetleri." href={`/komisyonlar/${key}`} key={key} />)}</div></div></section></PageShell>;
}

export function ProjectsPage() { return <PageShell title="Projeler / Faaliyetler" eyebrow="Üretim alanlarımız" description="Kentimiz için geliştirdiğimiz projeler, faaliyetler ve ortak çalışmalar."><section className="section"><div className="container"><SectionHeading eyebrow="Projeler" title="Fikirden faaliyete." text="Kent Konseyi’nin meclis ve komisyonlarıyla birlikte yürüttüğü çalışmaları inceleyin." /><div className="project-grid">{['Mahalle Buluşmaları', 'Gençlik Kent Atölyesi', 'Yeşil Küçükçekmece', 'Erişilebilir Kent', 'Kültür ve Sanat Günleri', 'Afet Farkındalık Programı'].map((title, index) => <article className="project-card" key={title}><span>0{index + 1}</span><h3>{title}</h3><p>Ortak akılla tasarlanan, Küçükçekmece’nin yaşamına değer katan çalışma.</p><a href="/iletisim" className="text-link">Projeyi incele <ArrowRight size={16} /></a></article>)}</div></div></section></PageShell>; }

export function NewsPage() { const [news, setNews] = useState<NewsItem[]>([]); useEffect(() => { fetchNews().then(setNews); }, []); return <PageShell title="Haberler / Bülten" eyebrow="Gündem" description="Kent Konseyi’nden duyurular, haberler, bültenler ve aylık gelişmeler."><section className="section"><div className="container"><div className="news-grid news-page-grid">{news.map((item) => <article className="news-card red" key={item.id}><div className="news-meta"><span>{item.category}</span><time>{formatNewsDate(item.published_at)}</time></div><h3>{item.title}</h3><p className="news-excerpt">{item.excerpt}</p><a href={`/haberler/${item.id}`} aria-label={item.title}><ArrowRight size={18} /></a></article>)}</div>{news.length === 0 && <div className="state-message">Henüz haber eklenmemiş.</div>}</div></section></PageShell>; }

export function DocumentsPage() { const docs = ['Kent Konseyi Tüzüğü', 'Genel Kurul Kararları', 'Yürütme Kurulu Kararları', 'Faaliyet Raporları', 'Meclis Yönetmelikleri', 'Komisyon Çalışma Raporları']; return <PageShell title="Belgeler" eyebrow="Arşiv" description="Tüzük, yönetmelik, rapor, karar ve çalışma belgeleri."><section className="section"><div className="container"><SectionHeading eyebrow="Belge arşivi" title="Açık ve erişilebilir bilgi." text="Kent Konseyi çalışmalarına ilişkin güncel belgeleri aşağıdan inceleyebilir veya indirebilirsiniz." /><div className="document-list">{docs.map((doc) => <a className="document-row" href="#belge" key={doc}><FileText size={20} /><span><strong>{doc}</strong><small>PDF · Güncel belge</small></span><Download size={17} /></a>)}</div></div></section></PageShell>; }

export function CalendarPage() { const [events, setEvents] = useState<EventItem[]>([]); useEffect(() => { fetchEvents().then(setEvents); }, []); return <PageShell title="Etkinlik Takvimi" eyebrow="Takvim" description="Toplantılar, çalıştaylar, meclis buluşmaları ve kent etkinlikleri."><section className="section"><div className="container"><SectionHeading eyebrow="Yaklaşan etkinlikler" title="Takviminize ekleyin." text="Kent Konseyi’nin yaklaşan tüm etkinliklerini burada bulabilirsiniz." /><div className="events-list">{events.map((item) => <EventRow item={item} key={item.id} />)}</div>{events.length === 0 && <div className="state-message">Yaklaşan etkinlik yok.</div>}</div></section></PageShell>; }

export function GalleryPage({ type = 'gallery' }: { type?: 'gallery' | 'video' }) { const video = type === 'video'; return <PageShell title={video ? 'Video Arşivi' : 'Fotoğraf Galerisi'} eyebrow="Arşiv" description={video ? 'Kent Konseyi çalışmalarından video kayıtları.' : 'Birlikte ürettiğimiz anlardan kareler.'}><section className="section"><div className="container"><SectionHeading eyebrow={video ? 'Video' : 'Galeri'} title={video ? 'Çalışmalarımızdan görüntüler.' : 'Birlikte ürettiğimiz anlar.'} /><div className="gallery-grid gallery-page-grid">{galleryImages.concat(galleryImages).map((image, index) => <a href="#galeri" className="gallery-tile" key={`${image}-${index}`}><img src={image} alt="Kent Konseyi etkinliği" />{video && <span className="play-badge"><Play size={15} /></span>}</a>)}</div></div></section></PageShell>; }

export function ContactPage() { return <PageShell title="Katılım / İletişim" eyebrow="Söz sende" description="Fikrinizi, önerinizi, gönüllülük başvurunuzu ve sorularınızı bize iletin."><section className="section"><div className="container contact-grid"><div><SectionHeading eyebrow="Bize ulaşın" title="Kent için sözünüzü paylaşın." text="Sizi dinlemek, birlikte üretmek ve Küçükçekmece’nin geleceğine katkı sunmak için buradayız." /><div className="contact-info"><p><MapPin size={18} /> Atatürk Mah. Kent Konseyi Merkezi<br />Küçükçekmece / İstanbul</p><p><Mail size={18} /> info@kucukcekmecekentkonseyi.org</p></div></div><form className="contact-form" onSubmit={(e) => e.preventDefault()}><label>Ad Soyad<input required /></label><label>E-posta<input type="email" required /></label><label>Başvuru türü<select><option>Fikrimi paylaşmak istiyorum</option><option>Gönüllü olmak istiyorum</option><option>Meclise katılmak istiyorum</option><option>Bilgi almak istiyorum</option></select></label><label>Mesajınız<textarea required /></label><button className="button button-dark" type="submit"><Send size={16} /> Gönder</button></form></div></section></PageShell>; }
